
// This file has been generated by the GUI designer. Do not modify.
namespace Game1
{
	public partial class MainWindow
	{
		private global::Gtk.HPaned hpaned1;

		private global::Gtk.VPaned vpaned1;

		private global::Microsoft.Xna.Framework.Gtk.RenderWidget rsFace1;

		private global::Microsoft.Xna.Framework.Gtk.RenderWidget rsFace3;

		private global::Gtk.VPaned vpaned2;

		private global::Microsoft.Xna.Framework.Gtk.RenderWidget rsFace2;

		private global::Microsoft.Xna.Framework.Gtk.RenderWidget rsFace4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Game1.MainWindow
			this.Name = "Game1.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Game1.MainWindow.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 1;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vpaned1 = new global::Gtk.VPaned();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 1;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.rsFace1 = new global::Microsoft.Xna.Framework.Gtk.RenderWidget();
			this.rsFace1.Name = "rsFace1";
			this.rsFace1.AutoDraw = false;
			this.rsFace1.AutoDrawInterval = 0;
			this.vpaned1.Add(this.rsFace1);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.rsFace1]));
			w1.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.rsFace3 = new global::Microsoft.Xna.Framework.Gtk.RenderWidget();
			this.rsFace3.Name = "rsFace3";
			this.rsFace3.AutoDraw = false;
			this.rsFace3.AutoDrawInterval = 0;
			this.vpaned1.Add(this.rsFace3);
			this.hpaned1.Add(this.vpaned1);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vpaned1]));
			w3.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vpaned2 = new global::Gtk.VPaned();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 1;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.rsFace2 = new global::Microsoft.Xna.Framework.Gtk.RenderWidget();
			this.rsFace2.Name = "rsFace2";
			this.rsFace2.AutoDraw = false;
			this.rsFace2.AutoDrawInterval = 0;
			this.vpaned2.Add(this.rsFace2);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.vpaned2[this.rsFace2]));
			w4.Resize = false;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.rsFace4 = new global::Microsoft.Xna.Framework.Gtk.RenderWidget();
			this.rsFace4.Name = "rsFace4";
			this.rsFace4.AutoDraw = false;
			this.rsFace4.AutoDrawInterval = 0;
			this.vpaned2.Add(this.rsFace4);
			this.hpaned1.Add(this.vpaned2);
			this.Add(this.hpaned1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
